  # CICD pipeline
  name: Automation CICD pipeline

  on:
    pull_request:
      branches: main

  jobs:
    test:
      runs-on: ubuntu-latest

      steps: 
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Install node
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Install dependencies and browsers
          run: |
            npm ci
            npx playwright install --with-deps

        - name: execute tests
          run: npx playwright test

        - name:  Generate and upload reports
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: playwright-report
            path: playwright-report
            retention-days: 3
        

